networks:
  network:
    driver: bridge
services:
  laminas:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - network
  redis:
    image: redis
    networks:
      - network
