<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Redis: <?= $this->vars('updated_at') ?></h1>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="<?= $this->url('redis.create') ?>">
        create
    </a>
    <a class="btn btn-primary btn-lg" href="<?= $this->url('redis.read') ?>">
        read
    </a>
    <a class="btn btn-primary btn-lg" href="<?= $this->url('redis.update') ?>">
        update
    </a>
    <a class="btn btn-primary btn-lg" href="<?= $this->url('redis.delete') ?>">
        delete
    </a>
</div>